from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import darkblue
from reportlab.lib.units import inch
from datetime import datetime


def generate_pdf(filename, requirement, response):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # ---------------- Title ----------------

    title = styles["Heading1"]
    title.alignment = TA_CENTER
    title.textColor = darkblue

    story.append(Paragraph("AI QA COPILOT REPORT", title))
    story.append(Paragraph("<br/><br/>", styles["Normal"]))

    # ---------------- Date ----------------

    date = datetime.now().strftime("%d %B %Y %H:%M")

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {date}",
            styles["Normal"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # ---------------- Requirement ----------------

    story.append(
        Paragraph("<b>Requirement</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(requirement.replace("\n", "<br/>"), styles["BodyText"])
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # ---------------- AI Response ----------------

    story.append(
        Paragraph("<b>Generated Test Cases</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(response.replace("\n", "<br/>"), styles["BodyText"])
    )

    story.append(Paragraph("<br/><br/>", styles["Normal"]))

    # ---------------- Footer ----------------

    story.append(
        Paragraph(
            "<b>Generated by AI QA Copilot</b>",
            styles["Heading3"]
        )
    )

    doc.build(story)

    return filename